/****************************************************************************/
/* DIET forwarder IDL description                                           */
/*                                                                          */
/*  Author(s):                                                              */
/*    - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)                         */
/*                                                                          */
/* $LICENSE$                                                                */
/****************************************************************************/
/* $Id$
 * $Log$
 * Revision 1.2  2010/12/03 12:40:26  kcoulomb
 * MAJ log to use forwarders
 *
 * Revision 1.5  2010/07/27 16:16:49  glemahec
 * Forwarders robustness
 *
 * Revision 1.4  2010/07/27 10:24:32  glemahec
 * Improve robustness & general performance
 *
 * Revision 1.3  2010/07/20 14:31:46  glemahec
 * Forwarder robustness + bug corrections
 *
 * Revision 1.2  2010/07/14 23:45:31  bdepardo
 * Header corrections
 *
 * Revision 1.1  2010/07/12 15:54:35  glemahec
 * DIET 2.5 beta 1 - Forwarder IDL files
 ****************************************************************************/

#ifndef FORWARDER_IDL
#define FORWARDER_IDL

#include "common_types.idl"

#include "LogComponentFwdr.idl"
#include "LogToolFwdr.idl"

interface Forwarder :
  ComponentConfiguratorForwarder
  , LogCentralComponentForwarder
  , ToolMsgReceiverForwarder
  , LogCentralToolForwarder
{	
	/* Get objects from the Forwarder. */
  //	ComponentConfigurator getComponentConfigurator (in string name);
	LogCentralComponent   getLogCentralComponent   (in string name);
	LogCentralTool getLogCentralTool(in string name);
	//        ToolMsgReceiver       getToolMsgReceiver       (in string name);
	//	LogCentralTool        getLogCentralTool        (in string name);

	/* Common methods. */
	//	long ping(in string objName)
	// raises(UnknownObject, BadNameException);
  oneway void getRequest(in corba_request_t req, in string objName);
  string getHostname(in string objName)
    raises(UnknownObject, BadNameException);

	/* CORBA remote management. */
	void bind(in string objName, in string ior);
	oneway void unbind(in string objName);
	//	SeqString getBindings(in string ctxt);
	
	/* Peer connection. */
	void connectPeer(in string ior, in string host, in long port);
	string getIOR();
	
	/* Obtain informations about this forwarder. */
	string getName();
//	SeqString acceptList();
//	SeqString rejectList();
	boolean manage(in string hostname);
	
	//	SeqString routeTree();


	/* Forwarders management. */
	/* traceRoute, ping, topology, ... */
	
};

#endif
