/**
 * @file AgentFwdr.idl
 *
 * @brief  DIET forwarder IDL description
 *
 * @author 
 *         - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENSE|
 */


#ifndef AGENTFWDR_IDL
#define AGENTFWDR_IDL

#include "Agent.idl"
#include "common_types.idl"

/**
 * @brief Agent interface
 * @class AgentFwdr
 */
interface AgentFwdr : Agent {

};

/**
 * @brief The forwarder version. For the documentation
 * of the class see Agent. All methods have
 * an objName param that represents the name of the
 * object, to know if it is local or distant
 */
interface AgentForwarder {
  long agentSubscribe(in string agentName, in string hostname,
                      in SeqCorbaProfileDesc_t services,
                      in string objName)
    raises(UnknownObject);
  long serverSubscribe(in string seDName,
                       in string hostname,
                       in SeqCorbaProfileDesc_t services,
                       in string objName)
    raises(UnknownObject);

  long childUnsubscribe(in unsigned long childID,
                        in SeqCorbaProfileDesc_t services,
                        in string objName)
    raises(UnknownObject);

  long childRemoveService(in unsigned long childID,
                          in corba_profile_desc_t profile,
                          in string objName)
    raises(UnknownObject);
  long addServices(in unsigned long myID,
                   in SeqCorbaProfileDesc_t services,
                   in string objName)
    raises(UnknownObject);

  oneway void getResponse(in corba_response_t resp,
                          in string objName);

  string getDataManager(in string objName)
    raises(UnknownObject);

};

#endif
