/**
 * @file Agent.idl
 *
 * @brief  DIET agent IDL description
 *
 * @author
 *         - Philippe COMBES (Philippe.Combes@ens-lyon.fr)
 *         - Sylvain DAHAN (Sylvain.Dahan@lifc.univ-fcomte.fr)
 *         - Frederic LOMBARD (Frederic.Lombard@lifc.univ-fcomte.fr)
 *
 * @section License
 *   |LICENSE|
 */


#ifndef _AGENT_IDL_
#define _AGENT_IDL_

#include "common_types.idl"
#include "response.idl"

/****************************************************************************/
/* Agent interface                                                          */
/****************************************************************************/
/**
 * @brief The agent interface
 * @section Agent
 */
interface Agent {

  /**
   * @brief Invoked by other agents to register as a child of this agent. As it is
   * useless to register without offering services, the last argument is the
   * same as for addServices method. Returns a registration number wich
   * indentifies the child amongst the other children of this agent.
   * @param agentName The name of the agent registering
   * @parent hostName The hostname
   * @param services Set of services (the services offered by the agent)
   * @return An id to identify the child among others
   */
  long agentSubscribe(in string agentName, in string hostname,
			       in SeqCorbaProfileDesc_t services);
  /**
   * @brief Invoked by servers to register as a child of this agent. As it is useless
   * to register without offering services, the last argument is the same as for
   * addServices method. Returns a registration number wich indentifies the
   * child amongst the other children of this agent.
   * @param seDName The name of the SeD registering
   * @parent hostName The hostname
   * @param services Set of services (the services offered by the agent)
   * @return An id to identify the child among others
   */
  long serverSubscribe(in string seDName,
                       in string hostname,
                       in SeqCorbaProfileDesc_t services);

  /** 
   * @brief Sends a request to the agent to commit suicide.
   * If "recursive" is true, then the agent forwards the request
   * to its children.
   * @param recursive If the children must remove to
   * @return An error code
   */
  long removeElement(in boolean recursive);
  /**
   * @brief To bind the agent to a parent
   * @param parentName The name of the parent to bind
   * @return An error code
   */
  long bindParent(in string parentName);
  /**
   * @brief To disconnect an element from the hierarchy.
   * @return An error code
   */
  long disconnect();

  /**
   * @brief Invoked by servers or LA to unregister as a child from this agent.
   * This also unregister the services offered by the child in the
   * service table of the agent.
   * @param childID The id of the child to remove
   * @param services The services offered by the child to eventually remove
   * @return An error code
   */
  long childUnsubscribe(in unsigned long childID,
			in SeqCorbaProfileDesc_t services);

  /**
   * @brief Invoked by SeDImpl::removeService(...) after removing a service
   * locally on a SeD. Used to inform the rest of the hierarchy that this
   * service is no longer available on this SeD.
   * @param childID The id of the SeD calling
   * @param profile The profile of the deleted SeD
   * @return An error code
   */
  long childRemoveService(in unsigned long childID,
			  in corba_profile_desc_t profile);

  /**
   * @brief Service table update method. Propagate the update of the problem list up
   * the tree when a new child registers. The first parameter is the child's
   * registration number.
   * @param myID The id of the child
   * @param services The services to add
   */
  long addServices(in unsigned long myID,
                   in SeqCorbaProfileDesc_t services);


  /**
   * @param Message posting functions:
   * This call is asynchronous. The response message REQ is kept in an
   * internal list and processed as soon as possible.
   * @param resp The response to add to the internal list to process later
   */
  oneway void getResponse(in corba_response_t resp);


  /** 
   * @brief Used to test if this agent is alive. 
   */
  long ping();

  /** 
   * @brief Used to get the host name of the Agent 
   * @return The hostname
   */
  string getHostname() ;
  /** 
   * @brief Used to get the data manager of the Agent 
   * @return The datamanager
   */
  string getDataManager();
  /**
   * @brief To search a data in the agent
   * @param request The request containing the dagda data
   */
  SeqString searchData(in string request);
};


#endif // _AGENT_IDL_

