/**
 * @file commonLogTypes.idl
 * @brief DIET IDL types for SeD registration and client request (init steps)     
 *                                                                          
 *  @author                                                             
 *    Philippe COMBES (Philippe.Combes@ens-lyon.fr)                       
 *    Frederic LOMBARD (Frederic.Lombard@lifc.univ-fcomte.fr)             
 *                                                                          
 * |LICENSE|
 */


#ifndef _COMMON_TYPES_IDL_
#define _COMMON_TYPES_IDL_

/**
 * @brief A sequence of any objects
 */
typedef sequence<any>    SeqAny;
/**
 * @brief A sequence of doubles
 */
typedef sequence<double> SeqDouble;
/**
 * @brief A sequence of long
 */
typedef sequence<long>   SeqLong;
/**
 * @brief A sequence of char
 */
typedef sequence<char>   SeqChar;
/**
 * @brief A sequence of string
 */
typedef sequence<string> SeqString;

/**
 * @brief The object name is not valid. 
 */
exception BadNameException {
  /**
   * @brief The "bad" name
   */
  string name;
  /**
   * @brief The function that raises the exception
   */
  string function;
  /**
   * @brief The name of the forwarder
   */
  string forwarder_name;
};
/**
 * @brief The name does not refer to a registered object. 
 */
exception UnknownObject {
  /**
   * @brief The unknown named object
   */
  string name;
};

/****************************************************************************/
/* DATA PERISTENCY: Data Description for Data Manager                       */
/****************************************************************************/

/**
 * @brief State of the data 
 */
enum occupationFlag {DIET_FREE, DIET_INUSE, DIET_TRANSFERT};
/**
 * @brief Flag used to manage data coherence: data only registered on one Data Manager
 */
enum kleenexFlag {DIET_ORIGINAL, DIET_KLEENEXCOPY};

/** 
 * @brief Structure of the Data Identifier 
 */
struct corba_data_id_t {
  /**
   * @brief The id of the data
   */
  string idNumber;
  /**
   * @brief A copy of the data
   */
  kleenexFlag dataCopy;
  /**
   * @brief How to handle the data
   */
  occupationFlag state;
};


/****************************************************************************/
/* REGISTRATON _ Data description                                           */
/* Mapping for the diet_data_desc_t type                                    */
/****************************************************************************/

/**
 * @brief Simple complex mapping 
 */
struct corba_scomplex_t {
  /**
   * @brief Real part
   */
  float r;
  /**
   * @brief Imaginary part
   */
  float i;
};
/**
 * @brief Double complex mapping 
 */
struct corba_dcomplex_t {
  /**
   * @brief Real part
   */
  double r;
  /**
   * @brief Imaginary part
   */
  double i;
};

/**
 * @brief Mapping for struct diet_scalar_specific 
 */
struct corba_scalar_specific_t {
  /**
   * @brief The value
   */
  any value;
};

/**
 * @brief Mapping for struct diet_vector_specific 
 */
struct corba_vector_specific_t {
  /**
   * @brief The size
   */
  long size;
};

/**
 * @brief Mapping fo structr diet_matrix_specific 
 */
struct corba_matrix_specific_t {
  /**
   * @brief The number of row
   */
  long nb_r;
  /**
   * @brief The number of column
   */
  long nb_c;
  /**
   * @brief The order
   */
  long order;
};

/**
 * @brief Mapping for struct diet_string_specific 
 */
struct corba_string_specific_t {
  long length;
};

/**
 * @brief Mapping for struct diet_paramstring_specific 
 */
struct corba_paramstring_specific_t {
  long length;
  string param;
};

/**
 * @brief Mapping for struct diet_file_specific 
 */
struct corba_file_specific_t {
  long size;
  string path;
};

/**
 * @brief Mapping for struct diet_container_specific 
 */
struct corba_container_specific_t {
  long size;
};

/**
 * @brief Descriptor
 * The field 'type' in diet_data_desc_t is the discriminant of union field
 */
union type switch (long) {
 case 0:
   corba_scalar_specific_t scal;
 case 1:
   corba_vector_specific_t vect;
 case 2:
   corba_matrix_specific_t mat;
 case 3:
   corba_string_specific_t str;
 case 4:
   corba_paramstring_specific_t pstr;
 case 5:
   corba_file_specific_t   file;
 case 6:
   corba_container_specific_t   cont;
};

/**
 * @brief Description of a data
 */
struct corba_data_desc_t {
/**
 * @brief The id of the data
 */
  corba_data_id_t id;
/**
 * @brief TODO
 */
  long mode;
/**
 * @brief TODO
 */
  long base_type;
/**
 * @brief TODO
 */
  type specific;
};
/**
 * @brief Sequence of corba data
 */
typedef sequence<corba_data_desc_t> SeqCorbaDataDesc_t;


/****************************************************************************/
/* REGISTRATON _ Service description                                        */
/****************************************************************************/

/** 
 * @brief Argument descriptor 
 */
struct corba_arg_desc_t {
  long base_type;
  long type;
};

/**
 * @brief server estimate aggregation
 */
struct corba_agg_default_t {
  octet dummy;
};

/**
 * @brief server estimate aggregation priority
 */
struct corba_agg_priority_t {
  sequence<long> priorityList;
};
/** New : The aggregator for user scheduler support.      */
/** The same as the default aggregator. Maybe not needed. */
/**********************************************************/
union corba_agg_specific_t switch (long) {
 case 0:
   corba_agg_default_t agg_default;
 case 1:
   corba_agg_priority_t agg_priority;
/** New : The aggregator for user scheduler support. */
/*****************************************************/
};

/**
 * @brief Descriptor for agregator
 */
struct corba_aggregator_desc_t {
  corba_agg_specific_t agg_specific;
};

/**
 * @brief Service profile descriptor (mapping for diet_profile_desc_t) 
 */
struct corba_profile_desc_t {
  string path;
  long   last_in;
  long   last_inout;
  long   last_out;
  sequence<corba_arg_desc_t> param_desc;
  corba_aggregator_desc_t aggregator;
};
/**
 * @brief A sequence of profile descriptor
 */
typedef sequence<corba_profile_desc_t> SeqCorbaProfileDesc_t;



/****************************************************************************/
/* REQUEST _ Problem profile description                                    */
/****************************************************************************/

/** 
 * @brief Mapping for diet_data_t 
 */
struct corba_data_t {
  corba_data_desc_t desc;
  SeqChar value;
};
/**
 * @brief A sequence of mapping for diet_data
 */
typedef sequence<corba_data_t> SeqCorbaData_t;

/**
 * @brief Actually, this is an equivalent to a diet_profile_t without the data.
 */
struct corba_pb_desc_t {
  string path;
  long   last_in;
  long   last_inout;
  long   last_out;
  SeqCorbaDataDesc_t param_desc;
};

/****************************************************************************/
/* REQUEST                                                                  */
/****************************************************************************/
/**
 * @brief A request is associated to an ID, a problem description, and a scheduler.
 */
struct corba_request_t {
  unsigned long     reqID;
  corba_pb_desc_t   pb;
  string            serialized_scheduler;
  long              max_srv;
};


/****************************************************************************/
/* ESTIMATION                                                               */
/****************************************************************************/
/**
 * @brief Custom estimation tags
 */
typedef short corba_est_tag_storage_t;

/**
 * @brief Custom estimation value
 */
struct corba_est_value_t {
  corba_est_tag_storage_t v_tag;
  short                   v_idx;
  double                  v_value;
};
/**
 * @brief A sequence of current estimation value
 */
typedef sequence <corba_est_value_t> SeqEstValue_t;

/**
 * @brief The estimation structure
 * commTimes == Communication times of ALL parameters :
 * the tranfer time of OUT parameters is estimated as if they were IN,
 * which is better than not taking them into account.
 *
 * totalTime stores all communication times + tComp
 */
struct corba_estimation_t {
  /* dynamic storage for performance estimation values */
  SeqEstValue_t estValues;
};


/****************************************************************************/
/* PROFILE (for problem solve)                                              */
/****************************************************************************/

/**
 * @brief The complete problem, sent from client to server. 
 */
struct corba_profile_t {
  long   last_in;
  long   last_inout;
  long   last_out;
  SeqCorbaData_t parameters;
  unsigned long dietReqID ;
  corba_estimation_t estim;
};

#endif // _COMMON_TYPES_IDL_

