/**
 * @file LocalAgentFwdr.idl
 *
 * @brief  DIET forwarder IDL description  
 *
 * @author
 *         - Gael Le Mahec   (gael.le.mahec@ens-lyon.fr)
 *
 * @section Licence
 *   |LICENSE|
 */


#ifndef LOCALAGENTFWDR_IDL
#define LOCALAGENTFWDR_IDL

#include "LocalAgent.idl"
#include "AgentFwdr.idl"

/**
 * @brief LocalAgent interface
 * @class LocalAgentFwdr
 */
interface LocalAgentFwdr : LocalAgent {

};

/**
 * @brief The forwarder version. For the documentation
 * of the class see LocalAgent. All methods have
 * an objName param that represents the name of the
 * object, to know if it is local or distant
 */
interface LocalAgentForwarder : AgentForwarder {
};

#endif
