/**
 * @file LogTypes.idl
 * @brief General type definitions used by the new LogService          
 *                                                              
 *  @author Georg Hoesch (hoesch@in.tum.de)                         
 *          Cyrille Pontvieux (cyrille.pontvieux@edu.univ-fcomte.fr)
 *  
 * @section License                                                            
 * |LICENSE|
 */
#ifndef _LOGTYPES_IDL_
#define _LOGTYPES_IDL_

/** This file defines important data structures that are
 *  used in LogService
 **/

/**
 * @brief Constant if all is ok
 */
const short LS_OK = 0;


// exact time definition with milliseconds
/**
 * @brief Structure to represent the time
 */
struct log_time_t {
  /**
   * @brief Seconds since EPOCH
   */
  long sec;       // seconds since EPOCH
  /**
   * @brief Milliseconds since 'sec'
   */
  long msec;      // milliseconds since 'sec'
};

// format for all messages
/**
 * @brief Representation of a message
 */
struct log_msg_t {
  /**
   * @brief The origin of the message
   */
  string componentName;   // origin of message
  /**
   * @brief The time of the message
   */
  log_time_t time;        // time of message
  /**
   * @brief True if the message has not been ordered
   */
  boolean warning;        // true if the message has not been ordered
  /**
   * @brief The type of the message
   */
  string tag;             // type of message
  /**
   * @brief The message
   */
  string msg;             // message content
};

// lists of important values
/**
 * @brief A set of log messages
 */
typedef sequence<log_msg_t> log_msg_buf_t;
/**
 * @brief A set of tags
 */
typedef sequence<string> tag_list_t;
/**
 * @brief A set of components
 */
typedef sequence<string> component_list_t;

#endif
