/*
 * @brief Defines the componentside interfaces needed by the new LogService
 *                                                                          
 *  @author Georg Hoesch (hoesch@in.tum.de)                                     
 *          Cyrille Pontvieux (cyrille.pontvieux@edu.univ-fcomte.fr)
 *
 * @section Licence
 * |LICENSE|                                                                
 */

#ifndef _LOGCOMPONENTFWDR_IDL_
#define _LOGCOMPONENTFWDR_IDL_

#include "LogTypes.idl"

#include "LogComponent.idl"

/* This file defines everything that is needed to attach a component to the
 * LogCentral.
 */

interface ComponentConfiguratorFwdr : ComponentConfigurator {

};

/**
 * @brief The forwarder version. For the documentation
 * of the class see @ref ComponentConfiguratorIDL. All methods have
 * an objName param that represents the name of the
 * object, to know if it is local or distant
 */
interface ComponentConfiguratorForwarder {
  void
  setTagFilter(in tag_list_t tagList, in string objName);
  void
  addTagFilter(in tag_list_t tagList, in string objName);
  void
  removeTagFilter(in tag_list_t tagList, in string objName);


};

interface LogCentralComponentFwdr : LogCentralComponent {

};

/**
 * @brief The forwarder version. For the documentation
 * of the class see @ref LogCentralComponentIDL. All methods have
 * an objName param that represents the name of the
 * object, to know if it is local or distant
 */
interface LogCentralComponentForwarder {
  short
  connectComponent(inout string componentName,
                   in string componentHostname,
                   in string message,
                   in string compConfigurator,
                   in log_time_t componentTime,
                   inout tag_list_t initialConfig,
		   in string objName);
  short
  disconnectComponent(in string componentName, in string message, in string objName);
  oneway void
  sendBuffer(in log_msg_buf_t buffer, in string objName);
  void
  synchronize(in string componentName, in log_time_t componentTime, in string objName);

};

#endif
